# Generated by Django 5.2.5 on 2025-08-17 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.BooleanField(default=True)),
                ('Fecha de creacion', models.DateTimeField(auto_now_add=True)),
                ('Fecha de modificacion', models.DateTimeField(auto_now=True)),
                ('Modificado por', models.IntegerField(blank=True, null=True)),
                ('Categoria', models.CharField(max_length=100, unique=True)),
                ('Descripcion', models.TextField(blank=True, null=True)),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['Categoria'],
            },
        ),
    ]
