# Generated by Django 5.2.5 on 2025-08-17 20:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='Categoria',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Descripcion',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Estado',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Fecha de creacion',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Fecha de modificacion',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Modificado por',
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
        migrations.AddField(
            model_name='category',
            name='modified_by',
            field=models.IntegerField(blank=True, null=True, verbose_name='Modificado por'),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=0, max_length=100, unique=True, verbose_name='Categoria'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion'),
        ),
    ]
