# Generated by Django 5.2.5 on 2025-08-17 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_alter_category_options_remove_category_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
