# Generated by Django 5.2.5 on 2025-08-20 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_subcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='Modificado por')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Marca')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='unitMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='Modificado por')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Unidad de Medida')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('modified_by', models.IntegerField(blank=True, null=True, verbose_name='Modificado por')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Codigo')),
                ('bar_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Codigo de Barras')),
                ('name', models.CharField(max_length=100, verbose_name='Producto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('last_purchase_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Ultimo Precio de Compra')),
                ('last_buy_date', models.DateField(blank=True, null=True, verbose_name='Ultima Fecha de Compra')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inv.brand')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inv.subcategory')),
                ('unitmeasure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inv.unitmeasure')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
                'unique_together': {('subcategory', 'name')},
            },
        ),
    ]
