# Generated by Django 5.2.5 on 2025-08-20 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0005_brand_unitmeasure_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='unitmeasure',
            new_name='unit_measure',
        ),
    ]
