# Generated by Django 5.2.5 on 2025-10-10 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_rename_unitmeasure_product_unit_measure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inv.brand'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inv.subcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_measure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inv.unitmeasure'),
            preserve_default=False,
        ),
    ]
