# Generated by Django 5.2.5 on 2025-10-01 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchaseorder_purchaseitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Impuesto'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Impuesto'),
        ),
    ]
