# Generated by Django 5.2.5 on 2025-10-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_saledetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observacion'),
        ),
    ]
