# Generated by Django 5.2.5 on 2025-10-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_observation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sequence_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='sale',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=100, unique=True, verbose_name='Numero de Factura'),
        ),
    ]
