# Generated by Django 5.2.5 on 2025-10-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_controlsequence_alter_sale_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Precio Unitario'),
            preserve_default=False,
        ),
    ]
