# Generated by Django 5.2.5 on 2025-10-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_saledetail_unit_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Impuesto'),
        ),
    ]
