# Generated by Django 5.2.5 on 2025-10-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_sale_discount_alter_sale_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Impuesto'),
        ),
    ]
