# Generated by Django 5.2.5 on 2025-10-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_sale_discount_alter_sale_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saledetail',
            options={'ordering': ['-sale__date'], 'permissions': [('supervisor_cashier_envoice', ' Permiso para agregar o quitar elementos de una factura (devoluciones)')], 'verbose_name': 'Detalle de Venta', 'verbose_name_plural': 'Detalles de Ventas'},
        ),
    ]
