# Generated by Django 5.2.5 on 2025-10-15 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_alter_saledetail_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date'], 'permissions': [('supervisor_cashier_envoice', ' Permiso para agregar o quitar elementos de una factura (devoluciones)')], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
        migrations.AlterModelOptions(
            name='saledetail',
            options={'ordering': ['-sale__date'], 'permissions': [('supervisor_cashier_envoice_detail', ' Permiso para agregar o quitar elementos de una factura (devoluciones)')], 'verbose_name': 'Detalle de Venta', 'verbose_name_plural': 'Detalles de Ventas'},
        ),
    ]
