# Generated by Django 5.2.5 on 2025-11-24 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_cashregister_dailyreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='down_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Pago Inicial / Adelanto'),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Credito', 'Crédito'), ('Tarjeta', 'Tarjeta')], default='Efectivo', max_length=50, verbose_name='Tipo de Pago'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_register_movements', to=settings.AUTH_USER_MODEL),
        ),
    ]
