# Generated by Django 5.2.5 on 2025-11-26 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_alter_cashregister_options_alter_cashregister_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='sales.sale'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='operation_type',
            field=models.CharField(choices=[('open', 'Apertura de Caja'), ('close', 'Cierre de Caja'), ('in', 'Ingreso de Efectivo'), ('out', 'Retiro de Efectivo'), ('sale', 'Venta')], max_length=10, verbose_name='Tipo de Operación'),
        ),
    ]
