# Generated by Django 5.2.5 on 2025-11-26 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_cashregister_sale_alter_cashregister_operation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashregister',
            options={'ordering': ['-date'], 'verbose_name': 'Movimiento de Caja', 'verbose_name_plural': 'Movimientos de Caja'},
        ),
        migrations.RemoveField(
            model_name='cashregister',
            name='sale',
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='operation_type',
            field=models.CharField(choices=[('open', 'Apertura de Caja'), ('close', 'Cierre de Caja'), ('in', 'Ingreso de Efectivo'), ('out', 'Retiro de Efectivo')], max_length=10, verbose_name='Tipo de Operación'),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
