# Generated by Django 5.2.5 on 2025-11-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_sale_cash_movement_alter_cashregister_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Venta'),
        ),
    ]
