# Generated by Django 5.2.5 on 2025-11-27 03:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_alter_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora'),
        ),
    ]
