# Generated by Django 5.2.5 on 2025-11-27 04:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_alter_cashregister_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Fecha y Hora'),
        ),
    ]
